bucket_prefix : joannah

s3main : 
  access_key : 
  access_secret : 
  region : mexico 
  endpoint : 
  port :  
  display_name : 
  email :  
  is_secure : 
  SSE : AES256

  s3dir : folder
  dir : ../data